name: tomahawk_space
description: "Приложение для просмотра изображений дня от NASA"
publish_to: 'none' # Убрать это при публикации в pub.dev

version: 1.4.1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  url_launcher: ^6.3.2 # ^6.2.2
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1 # ^3.2.0
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  dynamic_color: ^1.7.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13 # ^2.4.6
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4 # 0.14.3


flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo_light.png
    - assets/icons/logo_dark.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon_mobile.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/icon_mobile.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/icons/icon_pc.png"
    icon_size: 48 # min: 48, max: 256, default: 48